### ISSUE TITLE
Prologue Map (Back-Up)

### ISSUE THREAD

**Issue by jabzneilfernandez05** [STI-App-Dev-2024/BSIT3.1A-PCEchoesGame#7]
https://dasmarinassti-my.sharepoint.com/:u:/g/personal/fernandez_232356_dasmarinas_sti_edu_ph/EdzVTTYBi1BCkxZ1UUJk86EB5lK-uA67x0tFKAYTfCWaVw?e=mw52c5

**Comment by BrianMS-IT** [comment]
[Updated](https://l.messenger.com/l.php?u=https%3A%2F%2Fdasmarinassti-my.sharepoint.com%2F%3Au%3A%2Fg%2Fpersonal%2Ffernandez_232356_dasmarinas_sti_edu_ph%2FEZJBQkT2Xs1AtgqPX4MmA6oBJY-1otgwXN5wJKaf2cDeAw%3Fe%3DxDKvOd&h=AT2hyrg7limZl9U4UP3Pa1LE1x8686adA_6De3N0REaUuLNLtPZc0scMmg6UwGoJuxxfPjh-PStzH4fcrw5wZvsXr9pFCCG2cqIYNcsEkqtx--YWmQ414e3kTVrKUDRDmHmEPAQEBcfhO-4AtbWJRw)
